### ISSUE TITLE
Not Working on Android

### ISSUE THREAD

**Issue by taatiq882** [kesha-antonov/react-native-zoom-reanimated#1]
On ios its working fine but on android its not working at all..

**Comment by rkostrab** [comment]
it's working well on android - just set `width` and `height` in style of Image object
```js
      ...
      const dimension = useWindowDimensions();
      ...
      <Zoom>
        <Image 
          source={{ uri }}
          resizeMode='contain'
          style={{
            flex: 1,
            width: dimension.width,
            height: dimension.width,
          }}/>
      </Zoom>
```

But I recommend to use [react-native-reanimated-zoom](https://github.com/intergalacticspacehighway/react-native-reanimated-zoom/issues). It's a bit better maintained...

**Comment by kesha-antonov** [comment]
> On ios its working fine but on android its not working at all.. 

Could you give more details please what's not working for you?

**Comment by kesha-antonov** [comment]
Uploaded new version. Please try `^1.1.0`

**Comment by OverStackedLab** [comment]
This library still not working on Android except by setting the width and height for the image. I also tried getting it to work on Android inside a Modal and that's also not working. Works great with iOS.
