### ISSUE TITLE
Zoomed element jumps off position when Pan Gesture starts (Android)

### ISSUE THREAD

**Issue by fede-s** [kesha-antonov/react-native-zoom-reanimated#15]
Hi, I'm using this library to zoom images.
I get the error while testing on a Motorola G52 with Android 12.
Works well on iphone simulator.

I have a fix for it. I can send a PR.

Basically when the gesture starts `event.translationX` and `event.translationY` have non zero values on Android, the value depends on how much zoom there is. The value on iphone simulator is always 0, which is what it is expected by the library.

The fix consists on listening to `Gesture.Pan().onStart()` to grab the initial values of `event.translationX` and `event.translationY` and use them as offsets for `Gesture.Pan().onUpdate()` and `Gesture.Pan().onEnd()`
And it works perfectly because if the initial value is 0 then we have the same result as now, but if the value is non zero it fixes the glitch.

**Comment by fede-s** [comment]
Added PR #16

**Comment by kesha-antonov** [comment]
Released: https://github.com/kesha-antonov/react-native-zoom-reanimated/releases/tag/1.3.3

**Comment by kesha-antonov** [comment]
<img width="339" alt="Screenshot 2023-12-02 at 13 27 25" src="https://github.com/kesha-antonov/react-native-zoom-reanimated/assets/11584712/31944c22-2cdd-48c4-91d0-8f4c2a24c184">

On iOS event.translationX is not null
