### ISSUE TITLE
Double tap is ignored when pictured is zoomed in on Android

### ISSUE THREAD

**Issue by marcopacurariu3** [kesha-antonov/react-native-zoom-reanimated#17]
Hello,

I noticed on Android that the double tap for zooming out does not work. 

**How to reproduce it:**
Zoom in on a FastImage (in my case) and then try to zoom out using double tap. It does not work, tap is ignored.

I have checked the code and I found out why and how it might be fixed.

**Why this happens?**
The Pan gesture is triggered instead of Tap gesture when the picture is zoomed in.

**How could it be fixed?**
Replace `return Gesture.Race(
      Gesture.Simultaneous(pinchGesture, panGesture),
      tapGesture
    )`

with `return Gesture.Race(
      Gesture.Simultaneous(pinchGesture, panGesture, tapGesture)
    )`
    
I'm not used to the Gesture implementation, but it seems that not allowing for tap simultaneously with pinch & pan creates this situation. I am using Android 13. I'm not 100% sure if that's the only solution, however I don't think it hurts allowing for double tap while simultaneously zooming if, if anyone would want to do so for any reason, the behaviour works fine from what I tested.

I would have created a PR for this, but I don't have write access to it.

Let me know what you think.

**Comment by kesha-antonov** [comment]
Hi,

thanks for proposed solution!
Can you make PR?

**Comment by marcopacurariu3** [comment]
I would love to, but as I mentioned in the first message, I don't have write access for publishing it. Could you help me with this?

**Comment by kesha-antonov** [comment]
> I would love to, but as I mentioned in the first message, I don't have write access for publishing it. Could you help me with this?

You don't need to have write access

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by kesha-antonov** [comment]
Please try new version
Added fix there

https://www.npmjs.com/package/react-native-zoom-reanimated?activeTab=versions

**Comment by marcopacurariu3** [comment]
@kesha-antonov, unfortunately for me still does not work the double-tam zoom out. Only the zoom in works. I guess you tried the zoom out and for you it works, right?

**Comment by kesha-antonov** [comment]
> @kesha-antonov, unfortunately for me still does not work the double-tam zoom out. Only the zoom in works. I guess you tried the zoom out and for you it works, right?

Sure.
On Pixel 7

The libraries could work differently on different devices

**Comment by alduzy** [comment]
Take a look at my PR: https://github.com/kesha-antonov/react-native-zoom-reanimated/pull/23
It solves the issue for me (tested on samsung device and pixel emulator).

**Comment by marcopacurariu3** [comment]
Thanks @alduzy! Yes, this is my proposed solution. So it was not only on my side then. I was not sure if it's not on my side only, because I was using this component inside of another one (a carousel/slider). I didn't have enough time to test this component outside of the slider.

Thanks for the PR!

**Comment by kesha-antonov** [comment]
@alduzy cool, thanks!
I'll test it on Pixel

**Comment by kesha-antonov** [comment]
> @alduzy cool, thanks! I'll test it on Pixel

It doesn't work correctly. More info in the PR

**Comment by kesha-antonov** [comment]
> return Gesture.Race( Gesture.Simultaneous(pinchGesture, panGesture, tapGesture) )

Proposed `return Gesture.Race( Gesture.Simultaneous(pinchGesture, panGesture, tapGesture) )` gives same - images zooms out on pan - that's not expected

**Comment by kesha-antonov** [comment]
Please try `1.4.3` and report is it fixes this issue
