### ISSUE TITLE
Is Reanimated 3 supported?

### ISSUE THREAD

**Issue by mi5ha** [kesha-antonov/react-native-zoom-reanimated#18]
I use Reanimated 3 in the project so when I try to install the lib it fails.

But I see this from package:

```
"devDependencies": {
    "react-native-reanimated": "^3.2.0",
},
"peerDependencies": {
    "react-native-reanimated": "^2.0.0"
}
```

Should peerDependencies be bumped to v3 also?

**Comment by kesha-antonov** [comment]
Which package manager do you use?

**Comment by mi5ha** [comment]
> Which package manager do you use?

@kesha-antonov NPM

**Comment by kesha-antonov** [comment]
Released new version. Please try 1.4.1

https://www.npmjs.com/package/react-native-zoom-reanimated/v/1.4.1?activeTab=versions

**Comment by mi5ha** [comment]
@kesha-antonov Works like a charm! Tnx
