### ISSUE TITLE
TypeScript issue

### ISSUE THREAD

**Issue by sektr63a** [kesha-antonov/react-native-zoom-reanimated#19]
Current style definitions are wrong

```
export interface ZoomProps {
  style?: StyleProp<ViewProps>;
  contentContainerStyle?: StyleProp<ViewProps>;
  ...
}
```

It should be

```
export interface ZoomProps {
  style?: StyleProp<ViewStyle>;
  contentContainerStyle?: StyleProp<ViewStyle>;
  ...
}
```

**Comment by kesha-antonov** [comment]
Could you submit PR?

**Comment by jayan2019** [comment]
Also facing one more type
`'Zoom' cannot be used as a JSX component.
  Its return type 'ReactNode' is not a valid JSX element.
    Type 'undefined' is not assignable to type 'Element | null'.ts(2786)`

I think  `React.ReactElement` will fix this instead of `React.ReactNode`

**Comment by onderbakirtas** [comment]
I think it can be good to mark this as closed since it seems to be resolved.
