### ISSUE TITLE
TypeError: (0 , _reactNativeReanimated.useSharedValue) is not a function

### ISSUE THREAD

**Issue by Etaliya** [kesha-antonov/react-native-zoom-reanimated#2]
![simulator_screenshot_7C259F6E-2415-4749-93E0-25BEEE72276D](https://user-images.githubusercontent.com/54949248/191451206-6af24b84-0864-4a03-a0f3-b6c84db0d8e7.png)

"react-native-zoom-reanimated": "^1.0.6",
"react-native-reanimated": "^1.13.1",
"react-native-gesture-handler": "^1.6.1",

**Comment by kesha-antonov** [comment]
`reanimated 1` is not supported

**Comment by SaeedZhiany** [comment]
> `reanimated 1` is not supported

@kesha-antonov I suggest mentioning the minimum version required by both peer dependencies in the repository's Readme file. you can even modify `package.json` file and replace the `*` with the desired versions:

```json
"peerDependencies": {
  "react-native-gesture-handler": "*", // replace this too
  "react-native-reanimated": "^2.0.0"
}
```

**Comment by kesha-antonov** [comment]
> > `reanimated 1` is not supported
> 
> 
> 
> @kesha-antonov I suggest mentioning the minimum version required by both peer dependencies in the repository's Readme file. you can even modify `package.json` file and replace the `*` with the desired versions:
> 
> 
> 
> ```json
> 
> "peerDependencies": {
> 
>   "react-native-gesture-handler": "*", // replace this too
> 
>   "react-native-reanimated": "^2.0.0"
> 
> }
> 
> ```

Good idea, thanks!

**Comment by SaeedZhiany** [comment]
@kesha-antonov 

according to [this commit](https://github.com/kesha-antonov/react-native-zoom-reanimated/commit/2f0f916e6d345a2d443096b01b555c7e925a2d4a) you only lock `react-native-reanimated` dependency. what about `react-native-gesture-handler`? is there any min version required for it? also please mention the version in the Readme file. if you tell me the min `react-native-gesture-handler` version, I can create a PR for it.

Also, `react-native-reanimated` v3.x.x is published. did you test your component using that version?

**Comment by kesha-antonov** [comment]
> @kesha-antonov 
> 
> 
> 
> according to [this commit](https://github.com/kesha-antonov/react-native-zoom-reanimated/commit/2f0f916e6d345a2d443096b01b555c7e925a2d4a) you only lock `react-native-reanimated` dependency. what about `react-native-gesture-handler`? is there any min version required for it? also please mention the version in the Readme file. if you tell me the min `react-native-gesture-handler` version, I can create a PR for it.
> 
> 
> 
> Also, `react-native-reanimated` v3.x.x is published. did you test your component using that version?

I don't know exact minimum version for rngh.

I tested with new rnr.

**Comment by SaeedZhiany** [comment]
> I don't know exact minimum version for rngh.

So please test your component with RNGH v1.x.x in a project. if it works it will be fine for now to have `"react-native-gesture-handler": "*"` in your `package.json`.

> I tested with new rnr.

then for more flexibility, we should use `"react-native-reanimated": ">2.0.0"` to support projects using RNR v3.x.x and other major future releases. of course, if you only want to stick with RNR v2 and v3, we can use `"react-native-reanimated": "^2.0.0 || ^3.0.0"`.

I'm ready to create a PR whenever you make your decision about both RNR and RNGH.

**Comment by SaeedZhiany** [comment]
@kesha-antonov 

I created a draft branch on [my fork](https://github.com/SaeedZhiany/react-native-zoom-reanimated/tree/update_readme_and_gitignore) you can see the result there. just need to specify RNGH version and it's ready to be a PR on your repository.

**Comment by SaeedZhiany** [comment]
@kesha-antonov 

> I don't know exact minimum version for rngh.

So please test your component with RNGH v1.x.x in a project. if it works it will be fine for now to have `"react-native-gesture-handler": "*"` in your `package.json`.

> I tested with new rnr.

then for more flexibility, we should use `"react-native-reanimated": ">2.0.0"` to support projects using RNR v3.x.x and other major future releases. of course, if you only want to stick with RNR v2 and v3, we can use `"react-native-reanimated": "^2.0.0 || ^3.0.0"`.

I created a draft branch on [my fork](https://github.com/SaeedZhiany/react-native-zoom-reanimated/tree/update_readme_and_gitignore) you can see the result there. Just need to specify RNGH version and it's ready to be a PR on your repository. I'll wait for you to tell me the desired version.
