### ISSUE TITLE
Allow props for scale value on double tap

### ISSUE THREAD

**Issue by ClementLevesque** [kesha-antonov/react-native-zoom-reanimated#25]
Currently the new scale is automatically calculated based on a ratio (width / height) and is clamped (1.4 to 1.5).

It would be worth it to allow to pass a props "scaleStep" to override such value. We could also imagine a minScale and maxScale props for other purpose that could also impact the clamped values.

**Comment by kesha-antonov** [comment]
Hi
You want to pass the fixed value ? For example, 1.7, 2 ?
So it would not be calculated based on dimensions ?

**Comment by ClementLevesque** [comment]
Hi !
Yes exactly, it is an override so I don't think it would be a problem to allow any number, don't you think so ?

**Comment by kesha-antonov** [comment]
> Hi ! Yes exactly, it is an override so I don't think it would be a problem to allow any number, don't you think so ?

Sure

**Comment by ClementLevesque** [comment]
@kesha-antonov tell me if you want me to make a PR

**Comment by kesha-antonov** [comment]
Yeah, sure, do it
I'll change naming of the props a little

**Comment by ClementLevesque** [comment]
Here is the PR #26
