### ISSUE TITLE
Typescript error with animationFunction props

### ISSUE THREAD

**Issue by ClementLevesque** [kesha-antonov/react-native-zoom-reanimated#27]
Hello 👋 

I get the following error with the latest version :

![Capture d’écran 2024-03-19 à 15 48 24](https://github.com/kesha-antonov/react-native-zoom-reanimated/assets/24827952/41c0220b-e08e-4932-a300-d75cc632fbfd)

It seems that there is a problem with the animationFunction type.

I think it can be fixed with the following type :

` animationFunction?: typeof withTiming;`

The PR is already ready if you're ok with that.

**Comment by ClementLevesque** [comment]
@kesha-antonov did you have a chance to have a look ?

**Comment by kesha-antonov** [comment]
Hi!

Added comment

**Comment by ClementLevesque** [comment]
@kesha-antonov it should be ok now 👍
