### ISSUE TITLE
Property 'minPointers' does not exist on type 'PinchGesture'

### ISSUE THREAD

**Issue by pmtu95** [kesha-antonov/react-native-zoom-reanimated#4]
I'm trying to use with typescript but I got this issue.

![image](https://i.ibb.co/FXHFzGV/Screenshot-2022-11-17-at-10-05-45.png)

Version used:
`"react-native-reanimated": "^2.12.0"`
`"react-native-gesture-handler": "^2.8.0"`

**Comment by kesha-antonov** [comment]
Yeah, I think we should remove these calls

https://docs.swmansion.com/react-native-gesture-handler/docs/api/gestures/pinch-gesture

I don't see their availability here

**Comment by kesha-antonov** [comment]
Fixed in 1.1.1
