### ISSUE TITLE
Reduce bounciness

### ISSUE THREAD

**Issue by eduardfarkas** [kesha-antonov/react-native-zoom-reanimated#7]
Hi, thank you for great package :)

Is there a way to reduce the bounciness? Or even remove it, the default settings are kinda too much for my purpose.

Thank you in advance

**Comment by kesha-antonov** [comment]
> Hi, thank you for great package :)
> 
> 
> 
> Is there a way to reduce the bounciness? Or even remove it, the default settings are kinda too much for my purpose.
> 
> 
> 
> Thank you in advance

Hi
Sure, I can do this configurable

**Comment by kesha-antonov** [comment]
Hi

I've added `animationFunction` & `animationConfig` to parameters: https://github.com/kesha-antonov/react-native-zoom-reanimated#parameters

Will release on npm soon

**Comment by kesha-antonov** [comment]
I've changed default animation to linear.
