### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by SaeedZhiany** [kesha-antonov/react-native-zoom-reanimated#9]
Thanks for the package. is there any plan to support Typescript or even rewrite the package with Typescript?

**Comment by kesha-antonov** [comment]
Hi,

yes, it's a good idea.
I can make it in a 2 weeks or you can make a PR

**Comment by SaeedZhiany** [comment]
I created a PR fro that. please review. https://github.com/kesha-antonov/react-native-zoom-reanimated/pull/10

**Comment by kesha-antonov** [comment]
Perfect!
Let's continue there
